name = "my_project"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["MyProject", "PentagonalNumberTheorem", "Aristotle"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
[[lean_lib]]
name = "MyProject"

[[lean_lib]]
name = "PentagonalNumberTheorem"

[[lean_lib]]
name = "Aristotle"
