name = "my_project"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["EulerPentagonalNumberTheorem_Franklin", "QSeries"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
[[lean_lib]]
name = "EulerPentagonalNumberTheorem_Franklin"

[[lean_lib]]
name = "QSeries"
srcDir = "Qseries_Aristotle_new"
